# Generated by Django 5.0.6 on 2026-04-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_wallet_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingfeepayment',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, help_text='5% of starting price', max_digits=12),
        ),
        migrations.AlterField(
            model_name='listingfeepayment',
            name='qr_ref',
            field=models.CharField(blank=True, help_text='QR payment reference', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listingfeepayment',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID used for payment', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, help_text='Winner must pay before this time', null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current wallet balance in ₹', max_digits=14),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='upi_id',
            field=models.CharField(help_text='Seller UPI ID for bank transfer', max_length=100),
        ),
    ]
